# Generated by Django 5.0.7 on 2025-02-05 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_number', models.CharField(max_length=50, verbose_name='رقم المبنى')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='عنوان المبنى')),
                ('number_of_floors', models.IntegerField(default=1, verbose_name='عدد الطوابق')),
                ('number_of_apartments', models.IntegerField(default=0, verbose_name='عدد الشقق')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم المستاجر')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('id_number', models.CharField(max_length=20, verbose_name='رقم الهوية')),
                ('workplace', models.CharField(blank=True, max_length=100, verbose_name='جهة العمل')),
                ('additional_notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.CharField(max_length=50, verbose_name='رقم الشقة')),
                ('num_of_rooms', models.IntegerField(verbose_name='عدد الغرف')),
                ('electricity_meter_number', models.CharField(max_length=50, verbose_name='رقم عداد الكهرباء')),
                ('water_meter_number', models.CharField(max_length=50, verbose_name='رقم عداد الماء')),
                ('status', models.CharField(choices=[('شاغرة', 'شاغرة'), ('مأهولة', 'مأهولة')], default='شاغرة', max_length=8, verbose_name='الحالة')),
                ('floor_number', models.IntegerField(default=1, verbose_name='رقم الطابق')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.building', verbose_name='المبنى')),
            ],
        ),
        migrations.CreateModel(
            name='RentalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=50, verbose_name='رقم العقد')),
                ('contract_start_date', models.DateField(verbose_name='تاريخ بداية العقد')),
                ('contract_end_date', models.DateField(verbose_name='تاريخ انتهاء العقد')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ الإيجار شهري')),
                ('payment_status', models.CharField(choices=[('Paid', 'مدفوع'), ('Unpaid', 'غير مدفوع'), ('Partial', 'مدفوع جزئي')], default='Unpaid', max_length=20, verbose_name='حالة الدفع')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع كتأمين')),
                ('additional_notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.apartment', verbose_name='الشقة')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.tenant', verbose_name='المستاجر')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=50, verbose_name='رقم العقد')),
                ('contract_start_date', models.DateField(verbose_name='تاريخ بداية العقد')),
                ('contract_end_date', models.DateField(verbose_name='تاريخ انتهاء العقد')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ الإيجار شهري')),
                ('payment_status', models.CharField(choices=[('Paid', 'مدفوع'), ('Unpaid', 'غير مدفوع'), ('Partial', 'مدفوع جزئي')], default='Unpaid', max_length=20, verbose_name='حالة الدفع')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع كتأمين')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rentals.apartment', verbose_name='الشقة')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rentals.tenant', verbose_name='المستاجر')),
            ],
        ),
    ]
