# Generated by Django 5.0.7 on 2025-02-06 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'الشقة', 'verbose_name_plural': 'الشقق'},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'العمارة', 'verbose_name_plural': 'العمارات'},
        ),
        migrations.RemoveField(
            model_name='rentalhistory',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='additional_notes',
        ),
        migrations.AddField(
            model_name='rentalhistory',
            name='active_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.activetenant', verbose_name='عقد الحالي'),
        ),
        migrations.AddField(
            model_name='rentalhistory',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='activetenant',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.building', verbose_name='العمارة'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('vacant', 'شاغرة'), ('occoupid', 'مأهولة')], default='vacant', max_length=8, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='عنوان العمارة'),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_number',
            field=models.CharField(max_length=50, verbose_name='رقم العمارة'),
        ),
    ]
