# Generated by Django 5.0.7 on 2025-02-08 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_alter_tenant_options_alter_tenant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activetenant',
            name='apartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_apartment', to='rentals.apartment', verbose_name='الشقة'),
        ),
        migrations.AlterField(
            model_name='activetenant',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_tenant', to='rentals.tenant', verbose_name='المستاجر'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('شاغرة', 'شاغرة'), ('مأهولة', 'مأهولة')], default='شاغرة', max_length=8, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='active_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='rentals.activetenant', verbose_name='العقد الحالي'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_history', to='rentals.apartment', verbose_name='الشقة'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartment_rental_history', to='rentals.tenant', verbose_name='المستاجر'),
        ),
    ]
