# Generated by Django 5.0.7 on 2025-02-08 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_alter_activetenant_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activetenant',
            name='apartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_tenant', to='rentals.apartment', verbose_name='الشقة'),
        ),
        migrations.AlterField(
            model_name='activetenant',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم العقد'),
        ),
        migrations.AlterField(
            model_name='activetenant',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_apartment', to='rentals.tenant', verbose_name='المستاجر'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='rentals.building', verbose_name='العمارة'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='contract_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم العقد'),
        ),
    ]
