# Generated by Django 5.0.7 on 2025-02-09 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_alter_activetenant_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activetenant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_apartment', to='rentals.tenant', verbose_name='المستاجر'),
        ),
    ]
