# Generated by Django 5.0.7 on 2025-02-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_alter_activetenant_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activetenant',
            name='contract_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم العقد'),
        ),
    ]
