# Generated by Django 5.0.7 on 2025-02-12 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_alter_activetenant_contract_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activetenant',
            options={'verbose_name': 'الايجار', 'verbose_name_plural': 'الايجارات'},
        ),
        migrations.AlterModelOptions(
            name='rentalhistory',
            options={'verbose_name': 'سجل الايجار', 'verbose_name_plural': 'سجل الايجارات'},
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('building', 'apartment_number')},
        ),
    ]
