# Generated by Django 5.0.7 on 2025-02-16 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_alter_activetenant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, verbose_name='رقم الغرفة')),
                ('electricity_meter_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم عداد الكهرباء')),
                ('water_meter_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم عداد الماء')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_rooms', to='rentals.building', verbose_name='العمارة')),
            ],
            options={
                'verbose_name': 'غرفة الخدمات',
                'verbose_name_plural': 'غرف الخدمات',
                'unique_together': {('building', 'room_number')},
            },
        ),
    ]
